# docker-compose.yml
version: '3.8' # Compose ファイルのバージョンを指定

services:
  # FastAPI バックエンドサービス
  backend:
    build: ./aiagentapi          # backend ディレクトリの Dockerfile を使ってビルド
    container_name: aiagentapi_v0_1_1 # コンテナ名を指定 (オプション)
    volumes:
      - ./aiagentapi/token:/app/token
    # ポートをホストに公開する必要は必ずしもない (Gradioから直接アクセスするため)
    # デバッグ用に公開する場合はコメントアウトを外す
    # ports:
    #   - "8000:8000"
    networks:
      - app-network           # このサービスが接続するネットワーク

  # Gradio フロントエンドサービス
  frontend:
    build: ./gradioui         # frontend ディレクトリの Dockerfile を使ってビルド
    container_name: gradioui_v0_1_1 # コンテナ名を指定 (オプション)
    ports:
      - "7860:7860"         # ホストのポート 7860 をコンテナのポート 7860 にマッピング
    environment:
      # Gradio アプリ (app.py) に FastAPI の URL を環境変数として渡す
      # 'backend' は上の services で定義した FastAPI サービスのキー (サービス名)
      # Docker の内部ネットワーク経由でアクセスするため、サービス名で名前解決できる
      - PROTOCOL=http
      - FASTAPI_SERVICE_NAME=backend
      - FASTAPI_PORT=8000
      - API_ENDPOINT_PATH=/my_root/v1/aiagent
    depends_on:
      - backend             # backend サービスが起動してから frontend を起動する
    networks:
      - app-network           # このサービスが接続するネットワーク

# コンテナ間通信に使用するネットワークを定義
networks:
  app-network:
    driver: bridge          # デフォルトのブリッジネットワークドライバを使用